<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-08-23T06:45:02Z" name="Default suite" finished-at="2018-08-23T06:46:05Z" duration-ms="63393">
    <groups>
    </groups>
    <test started-at="2018-08-23T06:45:02Z" name="Default test" finished-at="2018-08-23T06:46:05Z" duration-ms="63393">
      <class name="com.aut.cura.TestLoginLogout_Negative">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.aut.cura.TestLoginLogout_Negative@65d09a04]" started-at="2018-08-23T12:15:02Z" name="beforeMethod" finished-at="2018-08-23T12:16:05Z" duration-ms="63178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="testMethod()[pri:0, instance:com.aut.cura.TestLoginLogout_Negative@65d09a04]" started-at="2018-08-23T12:16:05Z" name="testMethod" finished-at="2018-08-23T12:16:05Z" duration-ms="47" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.aut.cura.pageObjects.LandingPage.lnk_menu(LandingPage.java:19)
	at com.aut.cura.TestLoginLogout_Negative.testMethod(TestLoginLogout_Negative.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.aut.cura.TestLoginLogout_Negative@65d09a04]" started-at="2018-08-23T12:16:05Z" name="afterMethod" finished-at="2018-08-23T12:16:05Z" duration-ms="102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.aut.cura.TestLoginLogout_Negative -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
